---

- name: install nginx related packages
  apt: pkg=nginx state=latest update_cache=yes cache_valid_time=3600
  tags: nginx

# Assumes wildcard SSL if using local storage.
- name: copy canvas ssl pem file
  copy: src='etc/ssl/certs/canvas.pem' dest='/etc/ssl/certs/canvas.pem' owner=root group=root mode=644
  notify: restart nginx service
  tags:
    - nginx
    - ssl

# Assumes wildcard SSL if using local storage.
- name: copy canvas ssl key file
  copy: src='etc/ssl/private/canvas.key' dest='/etc/ssl/private/canvas.key' owner=root group=ssl-cert mode=640
  notify: restart nginx service
  tags:
    - nginx
    - ssl

- name: create nginx canvas cache directory
  file: path=/var/cache/nginx/canvas state=directory owner=www-data group=www-data mode=0755
  notify: restart nginx service
  tags: nginx

- name: remove default nginx sites
  file: path={{ item }} state=absent
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  notify: restart nginx service
  tags: nginx

- name: configure nginx
  template: src=etc/nginx/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx service
  tags: nginx

- name: configure canvas nginx site
  template: src=etc/nginx/sites-available/canvas.j2 dest=/etc/nginx/sites-available/canvas
  notify: restart nginx service
  tags: nginx

- name: create symlink /etc/nginx/sites-available/canvas to /etc/nginx/sites-enabled/canvas
  file: src=/etc/nginx/sites-available/canvas dest=/etc/nginx/sites-enabled/canvas state=link
  notify: restart nginx service
  tags: nginx
